import React from 'react';
import { Zap, BarChart3, Shield } from 'lucide-react';
import JobPageLayout, { type JobPageContent } from './JobPageLayout';
import type { Lang } from '../../i18n/usePageContent';

const content: Record<Lang, JobPageContent> = {
  da: {
    seoTitle: 'Freelance Sælger Strøm & Energioptimering | Magnora Marketing',
    seoDesc: 'Bliv freelance sælger af strøm og energioptimering til B2B og B2C kunder hos Magnora Marketing. Arbejd hjemmefra med fleksible tider og attraktiv provision.',
    heroTitle: 'Freelance Sælger – Strøm & Energioptimering',
    heroSubtitle: 'Hjælp private og erhvervskunder med at spare penge på deres energiregning. Et produkt alle har brug for – og du kan sælge det hjemmefra med stærk provision.',
    applyCta: 'Søg stillingen',
    allJobs: 'Se alle stillinger',
    aboutTitle: 'Hvad går jobbet ud på?',
    aboutP1: 'Som freelance sælger inden for strøm og energioptimering kontakter du private husstande og erhvervsvirksomheder med et enkelt budskab: vi kan hjælpe dig med at betale mindre for din strøm. Det er et produkt alle har brug for, og mange er lydhøre.',
    aboutP2: 'Magnora Marketing sørger for leads og scripts. Du tager kontakten, forklarer besparelsespotentialet og lukker aftalen eller booker et opfølgningsmøde.',
    tasks: [
      'Telefonsalg til private og erhvervskunder (B2B og B2C)',
      'Præsentation af energiaftaler og prissammenligninger',
      'Rådgivning om energioptimering og besparelsesmuligheder',
      'Lukke aftaler direkte eller booke opfølgningsmøder',
      'Rapportering og løbende opfølgning på pipeline',
    ],
    factsTitle: 'Stillingens nøglefakta',
    facts: [
      { label: 'Ansættelsesform', value: 'Freelance / selvstændig' },
      { label: 'Arbejdssted', value: 'Hjemmefra – hele Danmark' },
      { label: 'Arbejdstid', value: 'Fleksibel – du bestemmer selv' },
      { label: 'Løn', value: 'Fast grundhonorar + provision' },
      { label: 'Produkt', value: 'Strøm & energioptimering (B2B/B2C)' },
      { label: 'Opstart', value: 'Hurtigst muligt' },
    ],
    sendApplication: 'Send din ansøgning',
    whyTitle: 'Hvorfor energisalg er en god forretning',
    why: [
      { title: 'Alle har brug for strøm', desc: 'Strøm er ikke et nicheprodukt – alle virksomheder og husstande betaler for det. Det giver dig et enormt marked.' },
      { title: 'Dokumenterede besparelser', desc: 'Kunder skifter leverandør når de ser konkrete tal. Du præsenterer besparelserne – de er nemme at forstå.' },
      { title: 'Gentagne salg og loyalitet', desc: 'Energiaftaler fornyes løbende. Dine kunder bliver til en stabil base der giver provision år efter år.' },
    ],
    getTitle: 'Hvad du får hos Magnora Marketing',
    get: [
      { title: 'Arbejd hjemmefra', desc: 'Sælg fra dit eget hjem uden transport og faste mødetider. Alt du skal bruge er en telefon og computer.' },
      { title: 'Provision på hvert salg', desc: 'Grundhonorar plus provision per lukket aftale. Energisalg giver hyppige salg og stabil indkomst.' },
      { title: 'Fleksible tider', desc: 'Tilrettelæg din salgsdag som du vil. Perfekt ved siden af studie, familie eller andet arbejde.' },
    ],
    lookForTitle: 'Det kigger vi efter',
    lookFor: [
      'Erfaring med telefonsalg eller B2C-salg er en fordel',
      'Evne til at formidle besparelser enkelt og troværdigt',
      'Selvdisciplin og drive til at nå dine mål',
      'Gode kommunikationsevner på dansk',
      'Kendskab til energimarkedet er ikke et krav – vi oplærer dig',
      'Motivation for at hjælpe kunder med at spare penge',
    ],
    howTitle: 'Sådan søger du',
    howP: 'Send en kort besked om dig selv. Ingen formel ansøgning kræves – vi vender tilbage inden for 2 hverdage.',
    contactNow: 'Kontakt Magnora Marketing nu',
    faqs: [
      { question: 'Hvem sælger jeg til?', answer: 'Du sælger strøm og energioptimering til både private (B2C) og virksomheder (B2B) i hele Danmark.' },
      { question: 'Kræver det energifaglig baggrund?', answer: 'Nej – Magnora Marketing oplærer dig i produkterne. Du skal primært have gode kommunikationsevner og salgsevner.' },
      { question: 'Er der store kunder der kan give store provisioner?', answer: 'Ja – erhvervskunder kan have meget høje energiforbrug, hvilket giver attraktive provisioner på større aftaler.' },
      { question: 'Kan jeg vælge kun at arbejde B2B eller B2C?', answer: 'Ja – du aftaler med Magnora Marketing hvilken del af markedet du ønsker at fokusere på.' },
      { question: 'Er der opkaldslister klar fra dag ét?', answer: 'Ja – Magnora Marketing leverer opkaldslister og kampagnematerialer, så du kan starte med det samme.' },
      { question: 'Kan jeg se et eksempel på et script?', answer: 'Ja – du modtager et gennemprøvet salgsskript ved opstart som du kan tilpasse din stil.' },
      { question: 'Hvad sker der ved et succes-salg eller booket møde?', answer: 'Du registrerer resultatet i vores system, og provisionen beregnes automatisk og udbetales månedligt.' },
      { question: 'Er der løbende coaching?', answer: 'Ja – Magnora Marketing\'s salgsledere holder regelmæssige coaching-sessioner og giver feedback på din salgsstil.' },
      { question: 'Kan jeg prøve stillingen i en kortere periode?', answer: 'Ja – de første 2-4 uger betragtes som en gensidig prøveperiode.' },
      { question: 'Hvad er den gennemsnitlige indkomst for en aktiv freelancer?', answer: 'Det afhænger af aktivitet og produkt. Aktive freelancere med gode resultater kan tjene et solidt supplement eller en fuld indkomst.' },
      { question: 'Kan jeg arbejde for Magnora Marketing og for andre bureauer?', answer: 'Som freelancer er du fri til at arbejde for andre, så længe der ikke er konkurrencekonflikt med Magnora Marketing\'s kunder.' },
      { question: 'Er der skriftlige kontrakter?', answer: 'Ja – alle samarbejder formaliseres med en klar freelance-aftale der beskriver vilkår, provision og forventninger.' },
      { question: 'Hvad sker der, hvis jeg ikke trives med produktet?', answer: 'Vi kan diskutere om du er bedre egnet til et andet produkt i Magnora Marketing\'s portfolio.' },
      { question: 'Hvad er Magnora Marketing\'s forventninger til mig som freelancer?', answer: 'Vi forventer selvdisciplin, professionel optræden og løbende kommunikation om aktivitet og resultater.' },
    ],
    ctaTitle: 'Klar til at sælge Danmarks vigtigste ressource?',
    ctaSubtitle: 'Kontakt Magnora Marketing og kom i gang med strøm- og energisalg der giver resultater fra dag ét.',
    sendApplicationShort: 'Send ansøgning',
    seeAllOpen: 'Se alle ledige stillinger',
  },
  en: {
    seoTitle: 'Freelance Sales Rep Electricity & Energy Optimisation | Magnora Marketing',
    seoDesc: 'Become a freelance sales rep for electricity and energy optimisation for B2B and B2C customers at Magnora Marketing. Work from home with flexible hours and attractive commission.',
    heroTitle: 'Freelance Sales Rep – Electricity & Energy Optimisation',
    heroSubtitle: 'Help private and business customers save money on their energy bill. A product everyone needs – and you can sell it from home with strong commission.',
    applyCta: 'Apply for the position',
    allJobs: 'See all positions',
    aboutTitle: 'What does the job involve?',
    aboutP1: 'As a freelance sales rep within electricity and energy optimisation, you contact private households and businesses with a simple message: we can help you pay less for your electricity. It is a product everyone needs, and many are receptive.',
    aboutP2: 'Magnora Marketing provides leads and scripts. You make the contact, explain the savings potential and close the deal or book a follow-up meeting.',
    tasks: [
      'Phone sales to private and business customers (B2B and B2C)',
      'Presenting energy agreements and price comparisons',
      'Advising on energy optimisation and savings opportunities',
      'Closing deals directly or booking follow-up meetings',
      'Reporting and ongoing pipeline follow-up',
    ],
    factsTitle: 'Key facts about the position',
    facts: [
      { label: 'Employment type', value: 'Freelance / self-employed' },
      { label: 'Location', value: 'From home – all of Denmark' },
      { label: 'Working hours', value: 'Flexible – you decide' },
      { label: 'Pay', value: 'Fixed base fee + commission' },
      { label: 'Product', value: 'Electricity & energy optimisation (B2B/B2C)' },
      { label: 'Start', value: 'As soon as possible' },
    ],
    sendApplication: 'Send your application',
    whyTitle: 'Why energy sales is a good business',
    why: [
      { title: 'Everyone needs electricity', desc: 'Electricity is not a niche product – all companies and households pay for it. That gives you an enormous market.' },
      { title: 'Documented savings', desc: 'Customers switch supplier when they see concrete numbers. You present the savings – they are easy to understand.' },
      { title: 'Repeat sales and loyalty', desc: 'Energy agreements are renewed continuously. Your customers become a stable base that gives commission year after year.' },
    ],
    getTitle: 'What you get at Magnora Marketing',
    get: [
      { title: 'Work from home', desc: 'Sell from your own home without commuting and fixed meeting times. All you need is a phone and computer.' },
      { title: 'Commission on every sale', desc: 'Base fee plus commission per closed deal. Energy sales gives frequent sales and stable income.' },
      { title: 'Flexible hours', desc: 'Arrange your sales day as you wish. Perfect alongside studies, family or other work.' },
    ],
    lookForTitle: 'What we look for',
    lookFor: [
      'Experience with phone sales or B2C sales is an advantage',
      'Ability to convey savings simply and credibly',
      'Self-discipline and drive to reach your goals',
      'Good communication skills',
      'Knowledge of the energy market is not a requirement – we train you',
      'Motivation to help customers save money',
    ],
    howTitle: 'How to apply',
    howP: 'Send a short message about yourself. No formal application required – we get back to you within 2 business days.',
    contactNow: 'Contact Magnora Marketing now',
    faqs: [
      { question: 'Who do I sell to?', answer: 'You sell electricity and energy optimisation to both private customers (B2C) and businesses (B2B) across all of Denmark.' },
      { question: 'Does it require an energy background?', answer: 'No – Magnora Marketing trains you in the products. You primarily need good communication and sales skills.' },
      { question: 'Are there large customers that can give large commissions?', answer: 'Yes – business customers can have very high energy consumption, which gives attractive commissions on larger deals.' },
      { question: 'Can I choose to work only B2B or B2C?', answer: 'Yes – you agree with Magnora Marketing which part of the market you want to focus on.' },
      { question: 'Are call lists ready from day one?', answer: 'Yes – Magnora Marketing provides call lists and campaign materials so you can start right away.' },
      { question: 'Can I see an example of a script?', answer: 'Yes – you receive a proven sales script at onboarding that you can adapt to your style.' },
      { question: 'What happens on a successful sale or booked meeting?', answer: 'You register the result in our system, and the commission is calculated automatically and paid monthly.' },
      { question: 'Is there ongoing coaching?', answer: 'Yes – Magnora Marketing\'s sales managers hold regular coaching sessions and give feedback on your sales style.' },
      { question: 'Can I try the position for a shorter period?', answer: 'Yes – the first 2-4 weeks are considered a mutual trial period.' },
      { question: 'What is the average income for an active freelancer?', answer: 'It depends on activity and product. Active freelancers with good results can earn a solid supplement or a full income.' },
      { question: 'Can I work for Magnora Marketing and for other agencies?', answer: 'As a freelancer you are free to work for others, as long as there is no competitive conflict with Magnora Marketing\'s clients.' },
      { question: 'Are there written contracts?', answer: 'Yes – all collaborations are formalised with a clear freelance agreement describing terms, commission and expectations.' },
      { question: 'What happens if I don\'t enjoy the product?', answer: 'We can discuss whether you are better suited to another product in Magnora Marketing\'s portfolio.' },
      { question: 'What are Magnora Marketing\'s expectations of me as a freelancer?', answer: 'We expect self-discipline, professional conduct and ongoing communication about activity and results.' },
    ],
    ctaTitle: 'Ready to sell Denmark\'s most important resource?',
    ctaSubtitle: 'Contact Magnora Marketing and get started with electricity and energy sales that deliver results from day one.',
    sendApplicationShort: 'Send application',
    seeAllOpen: 'See all open positions',
  },
  es: {
    seoTitle: 'Vendedor Freelance Electricidad y Optimización Energética | Magnora Marketing',
    seoDesc: 'Conviértete en vendedor freelance de electricidad y optimización energética para clientes B2B y B2C en Magnora Marketing. Trabaja desde casa con horarios flexibles y comisión atractiva.',
    heroTitle: 'Vendedor Freelance – Electricidad y Optimización Energética',
    heroSubtitle: 'Ayuda a clientes particulares y empresas a ahorrar dinero en su factura energética. Un producto que todos necesitan – y puedes venderlo desde casa con buena comisión.',
    applyCta: 'Solicitar el puesto',
    allJobs: 'Ver todas las vacantes',
    aboutTitle: '¿En qué consiste el trabajo?',
    aboutP1: 'Como vendedor freelance en electricidad y optimización energética, contactas con hogares particulares y empresas con un mensaje sencillo: podemos ayudarte a pagar menos por tu electricidad. Es un producto que todos necesitan, y muchos son receptivos.',
    aboutP2: 'Magnora Marketing se encarga de los leads y los guiones. Tú haces el contacto, explicas el potencial de ahorro y cierras el acuerdo o reservas una reunión de seguimiento.',
    tasks: [
      'Venta telefónica a clientes particulares y empresas (B2B y B2C)',
      'Presentación de acuerdos energéticos y comparativas de precios',
      'Asesoramiento sobre optimización energética y oportunidades de ahorro',
      'Cierre de acuerdos directamente o reserva de reuniones de seguimiento',
      'Informes y seguimiento continuo del pipeline',
    ],
    factsTitle: 'Datos clave del puesto',
    facts: [
      { label: 'Tipo de contrato', value: 'Freelance / autónomo' },
      { label: 'Lugar de trabajo', value: 'Desde casa – toda Dinamarca' },
      { label: 'Horario', value: 'Flexible – tú decides' },
      { label: 'Retribución', value: 'Base fija + comisión' },
      { label: 'Producto', value: 'Electricidad y optimización energética (B2B/B2C)' },
      { label: 'Inicio', value: 'Lo antes posible' },
    ],
    sendApplication: 'Envía tu solicitud',
    whyTitle: 'Por qué la venta de energía es un buen negocio',
    why: [
      { title: 'Todos necesitan electricidad', desc: 'La electricidad no es un producto de nicho – todas las empresas y hogares la pagan. Eso te da un mercado enorme.' },
      { title: 'Ahorros documentados', desc: 'Los clientes cambian de proveedor cuando ven cifras concretas. Tú presentas los ahorros – son fáciles de entender.' },
      { title: 'Ventas repetidas y fidelidad', desc: 'Los acuerdos energéticos se renuevan continuamente. Tus clientes se convierten en una base estable que da comisión año tras año.' },
    ],
    getTitle: 'Lo que obtienes en Magnora Marketing',
    get: [
      { title: 'Trabaja desde casa', desc: 'Vende desde tu propia casa sin desplazamientos ni horarios de reunión fijos. Todo lo que necesitas es un teléfono y un ordenador.' },
      { title: 'Comisión por cada venta', desc: 'Base fija más comisión por acuerdo cerrado. La venta de energía da ventas frecuentes e ingresos estables.' },
      { title: 'Horario flexible', desc: 'Organiza tu jornada de venta como quieras. Perfecto junto a los estudios, la familia u otro trabajo.' },
    ],
    lookForTitle: 'Lo que buscamos',
    lookFor: [
      'La experiencia en venta telefónica o venta B2C es una ventaja',
      'Capacidad de transmitir el ahorro de forma sencilla y creíble',
      'Autodisciplina y empuje para alcanzar tus objetivos',
      'Buenas habilidades de comunicación',
      'El conocimiento del mercado energético no es un requisito – te formamos',
      'Motivación por ayudar a los clientes a ahorrar dinero',
    ],
    howTitle: 'Cómo solicitarlo',
    howP: 'Envía un mensaje breve sobre ti. No se requiere solicitud formal – te respondemos en un plazo de 2 días laborables.',
    contactNow: 'Contacta con Magnora Marketing ahora',
    faqs: [
      { question: '¿A quién vendo?', answer: 'Vendes electricidad y optimización energética tanto a particulares (B2C) como a empresas (B2B) en toda Dinamarca.' },
      { question: '¿Se requiere formación energética?', answer: 'No – Magnora Marketing te forma en los productos. Principalmente necesitas buenas habilidades de comunicación y de venta.' },
      { question: '¿Hay clientes grandes que puedan dar comisiones grandes?', answer: 'Sí – los clientes empresariales pueden tener un consumo energético muy alto, lo que da comisiones atractivas en acuerdos más grandes.' },
      { question: '¿Puedo elegir trabajar solo B2B o B2C?', answer: 'Sí – acuerdas con Magnora Marketing en qué parte del mercado quieres centrarte.' },
      { question: '¿Hay listas de llamadas listas desde el primer día?', answer: 'Sí – Magnora Marketing proporciona listas de llamadas y materiales de campaña para que puedas empezar de inmediato.' },
      { question: '¿Puedo ver un ejemplo de guion?', answer: 'Sí – recibes un guion de ventas probado al incorporarte que puedes adaptar a tu estilo.' },
      { question: '¿Qué ocurre con una venta exitosa o una reunión reservada?', answer: 'Registras el resultado en nuestro sistema, y la comisión se calcula automáticamente y se paga mensualmente.' },
      { question: '¿Hay coaching continuo?', answer: 'Sí – los responsables de ventas de Magnora Marketing realizan sesiones de coaching periódicas y dan feedback sobre tu estilo de venta.' },
      { question: '¿Puedo probar el puesto durante un periodo más corto?', answer: 'Sí – las primeras 2-4 semanas se consideran un periodo de prueba mutuo.' },
      { question: '¿Cuál es el ingreso medio de un freelance activo?', answer: 'Depende de la actividad y del producto. Los freelance activos con buenos resultados pueden ganar un buen complemento o un ingreso completo.' },
      { question: '¿Puedo trabajar para Magnora Marketing y para otras agencias?', answer: 'Como freelance eres libre de trabajar para otros, siempre que no haya conflicto de competencia con los clientes de Magnora Marketing.' },
      { question: '¿Hay contratos por escrito?', answer: 'Sí – todas las colaboraciones se formalizan con un acuerdo de freelance claro que describe las condiciones, la comisión y las expectativas.' },
      { question: '¿Qué ocurre si el producto no me convence?', answer: 'Podemos analizar si encajas mejor con otro producto de la cartera de Magnora Marketing.' },
      { question: '¿Qué espera Magnora Marketing de mí como freelance?', answer: 'Esperamos autodisciplina, conducta profesional y comunicación continua sobre la actividad y los resultados.' },
    ],
    ctaTitle: '¿Listo para vender el recurso más importante de Dinamarca?',
    ctaSubtitle: 'Contacta con Magnora Marketing y empieza con la venta de electricidad y energía que da resultados desde el primer día.',
    sendApplicationShort: 'Enviar solicitud',
    seeAllOpen: 'Ver todas las vacantes disponibles',
  },
};

export default function EnergySalesPage() {
  return (
    <JobPageLayout
      content={content}
      canonical="/jobs/energi-salg"
      keywords="freelance sælger strøm, energioptimering salg, strøm sælger job, energiaftalr B2B, Magnora Marketing energi stilling"
      backgroundImage="https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
      accent="orange"
      whyIcons={[
        <Zap size={36} className="text-orange-500" />,
        <BarChart3 size={36} className="text-orange-500" />,
        <Shield size={36} className="text-orange-500" />,
      ]}
    />
  );
}
